# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chat-react',
                'doc_host': 'https://ababino.github.io',
                'git_url': 'https://github.com/ababino/chat-react',
                'lib_path': 'chat_react'},
  'syms': {'chat_react.core': {'chat_react.core.foo': ('core.html#foo', 'chat_react/core.py')}}}
