# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['hm', 'aim', 'parse_prompt', 'chat_create']

# %% ../nbs/00_core.ipynb 3
import os
import openai

# %% ../nbs/00_core.ipynb 5
def hm(content): return {'role': 'user', 'content': content}

# %% ../nbs/00_core.ipynb 6
def aim(content): return {'role': 'assistant', 'content': content}

# %% ../nbs/00_core.ipynb 7
def parse_prompt(text):
    text = text.strip()
    messages = []
    for line in text.split('\n'):
        if line.startswith('user: '):
            messages.append(hm(line[6:]))
        elif line.startswith('assistant: '):
            messages.append(aim(line[11:]))
        else:
            messages[-1]['content'] += '\n' + line
    return messages

# %% ../nbs/00_core.ipynb 9
def chat_create(messages, model='gpt-3.5-turbo', temperature=0):
    response = openai.ChatCompletion().create(api_key=os.environ['OPENAI_KEY'], messages=messages, model=model, temperature=temperature)
    return response['choices'][0]['message']['content']
